Repository ixofoundation/ixo-webclient, pull requests merged in 2022-06, with the labels that each got.

#730 Work in Progress Bonds creation feature
  configs/testzone/app-config.json
  package.json
  src/assets/images/ring.svg
  src/common/components/ControlPanel/Actions/CreateBondModal.tsx
  src/common/components/InlineSwitch/InlineSwitch.styles.ts
  src/common/components/InlineSwitch/InlineSwitch.tsx
  src/common/components/JsonForm/CustomTemplates/ObjectFieldTemplate.tsx
  src/common/components/JsonForm/CustomWidgets/BaseBondingCurve/BaseBondingCurve.styles.ts
  src/common/components/JsonForm/CustomWidgets/BaseBondingCurve/BaseBondingCurve.tsx
  src/common/components/JsonForm/types.ts
  src/modules/Account/Account.utils.ts
  src/modules/Entities/CreateEntity/CreateTemplate/CreateTemplate.action.ts
  src/modules/Entities/CreateEntity/CreateTemplate/CreateTemplate.container.tsx
  src/modules/Entities/CreateEntity/CreateTemplate/CreateTemplate.reducer.ts
  src/modules/Entities/CreateEntity/CreateTemplate/CreateTemplate.selectors.ts
  src/modules/Entities/CreateEntity/CreateTemplate/components/ConfigureAlphaBondCard/ConfigureAlphaBondCard.tsx
  src/modules/Entities/CreateEntity/CreateTemplate/components/ConfigureAlphaBondCard/index.ts
  src/modules/Entities/CreateEntity/CreateTemplate/types.ts
  src/modules/Entities/CreateEntity/types.ts
  src/modules/relayer/relayer.selectors.ts
  src/modules/relayer/types.ts
Labels: Ready for review, Under review

#921 Fix:[IXO-914] change default filter for project explorer
  configs/testzone/config.json
Labels: Checks Failing

#936 LaunchPad Sprint
  src/common/components/Tabs/Tabs.tsx
Labels: WIP
