Repository ixofoundation/ixo-webclient, pull requests merged in 2024-02, with the labels that each got.

#1494 chore: fix uploads
  .circleci/config.yml
  .github/workflows/deploy-to-dev-on-merge.yml
  apps/web/src/components/Modals/CreatorSetupModal/CreatorSetupModal.tsx
  apps/web/src/components/Modals/ImageUploadModal/ImageUploadModal.tsx
  apps/web/src/hooks/createEntity.ts
  apps/web/src/pages/CreateEntity/Forms/PropertiesForm/SetupPageContent/Tools/CustomImage.tsx
  apps/web/src/redux/submitEntityClaim/submitEntityClaim.actions.ts
Labels: Ready for review

#1500 Feature/testing feedback
  .github/workflows/deploy-pr-deploy-preview.yml
  .github/workflows/deploy-to-dev-on-merge.yml
  apps/web/src/hooks/createEntity.ts
  apps/web/src/hooks/editEntity.ts
  apps/web/src/utils/entities.ts
Labels: Ready for review

#1501 fix: use multiclient sdk cellnode queries instead of api-module
  src/components/Modals/CreatorSetupModal/CreatorSetupModal.tsx
  src/components/Modals/ImageUploadModal/ImageUploadModal.tsx
  src/generated/graphql.tsx
  src/hooks/createEntity.ts
  src/pages/CreateEntity/Forms/PropertiesForm/SetupPageContent/Tools/CustomImage.tsx
  src/redux/submitEntityClaim/submitEntityClaim.actions.ts
Labels: Ready for review

#1502 chore: set correct relayer nodes for marketplaces
  .github/workflows/deploy-pr-deploy-preview.yml
  .github/workflows/deploy-to-dev-on-merge.yml
Labels: Ready for review

#1506 chore: add env vars at build step
  .github/workflows/deploy-pr-deploy-preview.yml
  .github/workflows/deploy-to-dev-on-merge.yml
  apps/web/src/routes/index.tsx
Labels: Ready for review

#1511 fix: fix date cutoff and submission of claim
  apps/web/src/lib/protocol/claim.ts
  apps/web/src/pages/CreateEntity/Components/DateRangePicker.tsx
  apps/web/src/pages/CurrentEntity/Dashboard/ProjectDashboard/Agents/AgentUsers/AgentUser.tsx
  apps/web/src/pages/CurrentEntity/Dashboard/ProjectDashboard/ClaimDetail/index.tsx
  apps/web/src/pages/CurrentEntity/Dashboard/ProjectDashboard/Claims/ClaimCollectionCreation/Scope.tsx
  apps/web/src/pages/CurrentEntity/Dashboard/ProjectDashboard/Claims/ClaimCollectionCreation/index.tsx
  apps/web/src/pages/CurrentEntity/Overview/ClaimForm/index.tsx
Labels: Ready for review

#1518 feature: qrcode of did in details control panel
  apps/web/src/components/ControlPanel/DidQRCode/DidQRCode.tsx
  apps/web/src/components/ControlPanel/DidQRCode/index.ts
  apps/web/src/components/ControlPanel/index.tsx
Labels: Ready for review

#1521 fix: entity creation navigation state
  apps/web/src/hooks/createEntityStepState.ts
  apps/web/src/hooks/stepperNavigation.ts
  apps/web/src/pages/CreateEntity/CreateEntity.tsx
  apps/web/src/pages/CreateEntity/EntityPages/SelectCreationProcess/SelectCreationProcess.tsx
  apps/web/src/pages/CreateEntity/EntityPages/SelectType/SelectType.tsx
  apps/web/src/pages/CreateEntity/EntityPages/SetupActions/SetupActions.tsx
  apps/web/src/pages/CreateEntity/EntityPages/SetupDataCollection/SetupDataCollection.tsx
  apps/web/src/pages/CreateEntity/EntityPages/SetupGroups/SetupGroups.tsx
  apps/web/src/pages/CreateEntity/EntityPages/SetupInstrument/SetupInstrument.tsx
  apps/web/src/pages/CreateEntity/EntityPages/SetupMetadata/SetupMetadata.tsx
  apps/web/src/pages/CreateEntity/EntityPages/SetupProperties/SetupProperties.tsx
  apps/web/src/redux/entityMultiStepCreation/slice.tsx
Labels: Ready for review

#1525 Feature/implement qr code design
  apps/web/src/assets/images/icon-mobile.svg
  apps/web/src/components/ControlPanel/DidQRCode/DidQRCode.css
  apps/web/src/components/ControlPanel/DidQRCode/DidQRCode.tsx
  apps/web/src/components/ControlPanel/index.tsx
Labels: Ready for review

#1527 Fix claim collection create
  apps/web/src/hooks/account.ts
  apps/web/src/lib/protocol/entity.ts
  apps/web/src/pages/CurrentEntity/Dashboard/ProjectDashboard/Claims/ClaimCollectionCreation/index.tsx
  apps/web/src/utils/encoding.ts
  apps/web/src/utils/entities.ts
  packages/wallet-connector/src/contexts/WalletContext.tsx
  packages/wallet-connector/src/hooks/wallet.ts
Labels: Ready for review

#1535 feat: collapsible footer
  apps/web/src/components/App/App.tsx
  apps/web/src/components/Footer/index.tsx
Labels: Ready for review

#1536 chore: fix dao transfer and add project transfer
  apps/web/src/pages/CurrentEntity/Dashboard/ProjectDashboard/EditEntity/index.tsx
  apps/web/src/pages/TransferEntity/TransferEntity.route.tsx
  apps/web/src/pages/TransferEntity/TransferEntityTo/index.tsx
  apps/web/src/pages/TransferEntity/index.tsx
  apps/web/src/router.tsx
  apps/web/src/routes/index.tsx
Labels: Ready for review

#1537 chore: upgrade multi client sdk and init only once
  apps/web/package.json
  apps/web/src/adapters/IxoSwapAdapter.ts
  apps/web/src/lib/protocol/cosmos.ts
  apps/web/src/lib/queryClient/index.ts
  apps/web/src/lib/queryClient/queryClient.ts
  apps/web/src/lib/singleton/index.ts
  apps/web/src/lib/singleton/singleton.ts
  apps/web/src/utils/multiContractCall.ts
  apps/web/src/utils/swap.ts
  yarn.lock
Labels: Ready for review

#1534 wip: display survery form on edit screen
  apps/web/src/hooks/editEntity.ts
  apps/web/src/pages/CurrentEntity/Dashboard/ClaimDashboard/EditEntity/index.tsx
  apps/web/src/pages/CurrentEntity/Dashboard/ClaimDashboard/index.tsx
  apps/web/src/pages/CurrentEntity/Dashboard/components/EditProfile.tsx
  apps/web/src/pages/CurrentEntity/Dashboard/components/EditSurveyTemplate.tsx
  apps/web/src/types/entities.ts
  apps/web/src/utils/entities.ts
Labels: Ready for review

#1528 chore:EdHeroes config removed and small change to IDCC footer
  apps/web/configs/edheroes/app-config.json
  apps/web/configs/edheroes/theme.json
  apps/web/configs/idcc/config.json
Labels: Ready for review

#1546 Chore/entity transfers
  apps/web/package.json
  apps/web/src/adapters/IxoSwapAdapter.ts
  apps/web/src/lib/protocol/cosmos.ts
  apps/web/src/lib/queryClient/index.ts
  apps/web/src/lib/queryClient/queryClient.ts
  apps/web/src/lib/singleton/index.ts
  apps/web/src/lib/singleton/singleton.ts
  apps/web/src/utils/multiContractCall.ts
  apps/web/src/utils/swap.ts
  yarn.lock
Labels: Ready for review, Ready to merge

#1552 Feature/implement new cosmwasm clients
  apps/web/package.json
  apps/web/src/adapters/IxoSwapAdapter.ts
  apps/web/src/components/Modals/DepositModal/DepositModal.tsx
  apps/web/src/components/Modals/GroupClaimModal/GroupClaimModal.tsx
  apps/web/src/components/Modals/GroupStakingModal/GroupStakingModal.tsx
  apps/web/src/components/Modals/GroupUnstakingModal/GroupUnstakingModal.tsx
  apps/web/src/components/Pages/Exchange/Swap/RenderSignStep.tsx
  apps/web/src/hooks/editEntity.ts
  apps/web/src/interfaces/cosmwasmClientBaseClass.ts
  apps/web/src/lib/protocol/bond.ts
  apps/web/src/lib/protocol/claim.ts
  apps/web/src/lib/protocol/cosmos.ts
  apps/web/src/lib/protocol/cosmwasm.ts
  apps/web/src/lib/protocol/entity.ts
  apps/web/src/lib/protocol/iid.messages.ts
  apps/web/src/lib/protocol/iid.ts
  apps/web/src/lib/queryClient/queryClient.ts
  apps/web/src/pages/CurrentEntity/Dashboard/DAODashboard/Governance/CreateProposal/ReviewProposal/ReviewProposal.tsx
  apps/web/src/pages/CurrentEntity/Dashboard/DAODashboard/Governance/GovernanceProposal.tsx
  apps/web/src/pages/CurrentEntity/Dashboard/DAODashboard/Governance/ProposalCard.tsx
  apps/web/src/pages/TransferEntity/TransferEntityReview/index.tsx
  apps/web/src/utils/multiContractCall.ts
  apps/web/src/utils/swap.ts
  packages/cosmwasm-clients/src/lib/Base.client.ts
  packages/cosmwasm-clients/src/lib/Cw20Base.client.ts
  packages/cosmwasm-clients/src/lib/Cw20Stake.client.ts
  packages/cosmwasm-clients/src/lib/Cw20StakeExternalRewards.client.ts
  packages/cosmwasm-clients/src/lib/Cw20StakeRewardDistributor.client.ts
  packages/cosmwasm-clients/src/lib/Cw4Group.client.ts
  packages/cosmwasm-clients/src/lib/Cw721Base.client.ts
  packages/cosmwasm-clients/src/lib/CwAdminFactory.client.ts
  packages/cosmwasm-clients/src/lib/CwFundDistributor.client.ts
  packages/cosmwasm-clients/src/lib/CwPayrollFactory.client.ts
  packages/cosmwasm-clients/src/lib/CwTokenSwap.client.ts
  packages/cosmwasm-clients/src/lib/CwVesting.client.ts
  packages/cosmwasm-clients/src/lib/DaoCore.client.ts
  packages/cosmwasm-clients/src/lib/DaoMigrator.client.ts
  packages/cosmwasm-clients/src/lib/DaoPreProposeApprovalSingle.client.ts
  packages/cosmwasm-clients/src/lib/DaoPreProposeApprover.client.ts
  packages/cosmwasm-clients/src/lib/DaoPreProposeMultiple.client.ts
  packages/cosmwasm-clients/src/lib/DaoPreProposeSingle.client.ts
  packages/cosmwasm-clients/src/lib/DaoProposalCondorcet.client.ts
  packages/cosmwasm-clients/src/lib/DaoProposalMultiple.client.ts
  packages/cosmwasm-clients/src/lib/DaoProposalSingle.client.ts
  packages/cosmwasm-clients/src/lib/DaoVotingCw20Staked.client.ts
  packages/cosmwasm-clients/src/lib/DaoVotingCw4.client.ts
  packages/cosmwasm-clients/src/lib/DaoVotingCw721Staked.client.ts
  packages/cosmwasm-clients/src/lib/DaoVotingNativeStaked.client.ts
  packages/cosmwasm-clients/src/lib/index.ts
  packages/cosmwasm-clients/tsconfig.json
  packages/cosmwasm-clients/vite.config.js
  packages/wallet-connector/src/hooks/wallet.ts
  turbo.json
Labels: Ready for review

#1559 Fix/924/idcc flow
  apps/web/package.json
  apps/web/src/components/ControlPanel/Actions/Actions.tsx
  apps/web/src/components/Modals/ApplyToJoinModal/ApplyToJoinModal.tsx
  apps/web/src/graphql/claims.ts
  apps/web/src/lib/protocol/claim.ts
  apps/web/src/pages/CurrentEntity/Dashboard/ProjectDashboard/ClaimDetail/index.tsx
Labels: Ready for review

#1560 fix: proposal premature success screen
  apps/web/src/pages/CurrentEntity/Dashboard/DAODashboard/Governance/CreateProposal/ReviewProposal/ReviewProposal.tsx
Labels: Ready for review

#1563 RELEASE 22/02/2024
  apps/web/configs/idcc/config.json
  apps/web/package.json
  apps/web/src/components/ControlPanel/Actions/Actions.tsx
  apps/web/src/components/Modals/ApplyToJoinModal/ApplyToJoinModal.tsx
  apps/web/src/graphql/claims.ts
  apps/web/src/lib/protocol/claim.ts
  apps/web/src/pages/CurrentEntity/Dashboard/DAODashboard/Governance/CreateProposal/ReviewProposal/ReviewProposal.tsx
  apps/web/src/pages/CurrentEntity/Dashboard/ProjectDashboard/ClaimDetail/index.tsx
Labels: Ready for review, RELEASE

#1568 Fix/adding linked claims
  apps/web/src/components/Modals/ClaimSelectModal/ClaimSelectModal.tsx
  apps/web/src/hooks/editEntity.ts
  apps/web/src/hooks/service.ts
  apps/web/src/utils/entities.ts
Labels: Ready for review

#1569 RELEASE 23/02/2024
  apps/web/src/components/ControlPanel/index.tsx
  apps/web/src/components/EntityCards/AssetCard/index.tsx
  apps/web/src/components/EntityCards/DaoCard/index.tsx
  apps/web/src/components/EntityCards/OracleCard/index.tsx
  apps/web/src/components/EntityCards/ProjectCard/index.tsx
  apps/web/src/components/Filters/Filters.styles.ts
  apps/web/src/components/Filters/IconListFilter/IconListFilterDesktop.tsx
  apps/web/src/components/Modals/ClaimSelectModal/ClaimSelectModal.tsx
  apps/web/src/hooks/editEntity.ts
  apps/web/src/hooks/service.ts
  apps/web/src/pages/CreateEntity/Components/Button.tsx
  apps/web/src/pages/CreateEntity/EntityPages/SetupGroups/SetupGroupSettings.tsx
  apps/web/src/utils/entities.ts
  apps/web/src/utils/getEntityIcon.tsx
Labels: Ready for review

#1572 Chore/change max size verbiage to correct limit
  apps/web/package.json
  apps/web/src/components/EntityCards/withEntityData.tsx
  apps/web/src/components/Modals/LinkedResourceSetupModal/LinkedResourceSetupModal.tsx
  apps/web/src/hooks/currentEntity.ts
  apps/web/src/pages/CreateEntity/Forms/PropertiesForm/SetupPageContent/Tools/CustomImage.tsx
  yarn.lock
Labels: Ready for review

#1574 fix: nullify checks from current entity
  apps/web/src/hooks/currentEntity.ts
Labels: Ready for review
